databases:
  - name: darkenyas_crm-db
    plan: free
    databaseName: darkenyas_crm
    ipAllowList: []  # only allow internal connections

services:
  - type: web
    name: darkenyas_crm
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djcrm.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: darkenyas_crm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "Darkenyas"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@darkenyas.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "Z*x*C*v*B*123"
